%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(phone).
-define(phone, true).

-define(phone_gpb_version, "4.4.0").

-ifndef('MSG_PB_H').
-define('MSG_PB_H', true).
-record(msg,
        {name                   :: iolist() | undefined % = 1
        }).
-endif.

-ifndef('PING_TOS_PB_H').
-define('PING_TOS_PB_H', true).
-record(ping_tos,
        {time                   :: integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PONG_TOC_PB_H').
-define('PONG_TOC_PB_H', true).
-record(pong_toc,
        {
        }).
-endif.

-ifndef('S_ROLE_PB_H').
-define('S_ROLE_PB_H', true).
-record(s_role,
        {role_id                :: integer() | undefined, % = 1, 32 bits
         role_name              :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('REGISTER_TOS_PB_H').
-define('REGISTER_TOS_PB_H', true).
-record(register_tos,
        {role_name              :: iolist() | undefined, % = 1
         psd                    :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('REGISTER_TOC_PB_H').
-define('REGISTER_TOC_PB_H', true).
-record(register_toc,
        {code                   :: integer() | undefined, % = 1, 32 bits
         role                   :: phone:s_role() | undefined % = 2
        }).
-endif.

-ifndef('LOGIN_TOS_PB_H').
-define('LOGIN_TOS_PB_H', true).
-record(login_tos,
        {role_name              :: iolist() | undefined, % = 1
         psd                    :: iolist() | undefined % = 2
        }).
-endif.

-ifndef('LOGIN_TOC_PB_H').
-define('LOGIN_TOC_PB_H', true).
-record(login_toc,
        {code                   :: integer() | undefined, % = 1, 32 bits
         role                   :: phone:s_role() | undefined % = 2
        }).
-endif.

-endif.
